name: run tests

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run all tests'
        required: true
        default: 'yes'

env:
  RSPM: https://packagemanager.posit.co/cran/latest  # Enables Linux binaries from Posit
  R_KEEP_PKG_SOURCE: yes  # Keeps sources for debugging if needed
  R_CALLR_ENV: full 

jobs:
  test-nCompile:
    runs-on: ubuntu-latest
    if: github.event.inputs.run_tests == 'yes'
    name: run tests

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'remotes::install_deps("actionsmre", dependencies = TRUE)'

      - name: Show useful info
        run: |
          Rscript -e '
            cat("Sys.which(\"R\"):", Sys.which("R"), "\n")
            print(.libPaths())
            cat("R.home():", R.home(), "\n")
            '

      - name: Install package
        run: R CMD INSTALL --install-tests actionsmre

      - name: Run tests
        run: |
          library(devtools)
          library(testthat)
          test_package("actionsmre")
        shell: Rscript {0}

